<a href="https://colab.research.google.com/github/answjddn005/Tensorflow-practice/blob/master/Conv_layers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 32, 28, 28, 5
n_filter = 10
k_size = 3

images = tf.random.uniform(minval=0, maxval=1,
                          shape=((N, n_H, n_W, n_C)))

conv = Conv2D(filters=n_filter, kernel_size=k_size)

output = conv(images)

W, B = conv.get_weights()

print(images.shape)
print(W.shape, B.shape)
print(output.shape)

(32, 28, 28, 5)
(3, 3, 5, 10) (10,)
(32, 26, 26, 10)


In [17]:
import numpy as np

N, n_H, n_W, n_C = 1, 5, 5, 3
n_filter = 1
k_size = 3

images = tf.random.uniform(minval=0, maxval=1,
                          shape=((N, n_H, n_W, n_C)))

conv = Conv2D(filters=n_filter, kernel_size=k_size)

output = conv(images)
print("Output(Tensorflow): \n", output.numpy().squeeze())
W, B = conv.get_weights()


images = images.numpy().squeeze()
W = W.squeeze()
#print(images.shape)
#print(W.shape)
#print(B.shape)

output_man = np.zeros(shape=(n_H - k_size + 1, n_W - k_size + 1))

for i in range(n_H - k_size + 1):
  for j in range(n_W - k_size + 1):
    window = images[i : i+k_size, j : j+k_size : ]
    output_man[i, j] = np.sum(window*W) + B


print("Output(Manual): \n", output_man)

Output(Tensorflow): 
 [[ 0.09284917 -0.5463467   0.02838326]
 [-0.35104084 -0.01369762  0.09858768]
 [ 0.31644168  0.74656457  0.37860683]]
(5, 5, 3)
(3, 3, 3)
(1,)
Output(Manual): 
 [[ 0.09284916 -0.54634678  0.02838328]
 [-0.35104081 -0.01369762  0.09858776]
 [ 0.31644174  0.74656451  0.3786068 ]]
