<a href="https://colab.research.google.com/github/answjddn005/Tensorflow-practice/blob/master/Conv_layer_with_filters.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 32, 28, 28, 3
n_filter = 5
k_size = 3

images = tf.random.uniform(minval=0, maxval=1,
                           shape=((N, n_H, n_W, n_C)))

conv = Conv2D(filters=n_filter, kernel_size=k_size)

Y = conv(images)

W, B = conv.get_weights()

print("Input Images: {}\n".format(images.shape))
print("W/B: {} / {}".format(W.shape, B.shape))
print("Output Image: {}".format(Y.shape))

Input Images: (32, 28, 28, 3)

W/B: (3, 3, 3, 5) / (5,)
Output Image: (32, 26, 26, 5)


In [24]:
import numpy as np

N, n_H, n_W, n_C = 1, 5, 5, 3
n_filter = 3
k_size = 4

images = tf.random.uniform(minval=0, maxval=1,
                           shape=((N, n_H, n_W, n_C)))


# Forward Propagation(Tensorflow)
conv = Conv2D(filters=n_filter, kernel_size=k_size, activation='sigmoid')
Y = conv(images)

Y = np.transpose(Y.numpy().squeeze(), (2, 0, 1))
print("Output(Tensorflow): \n", Y)

W, B = conv.get_weights()

# Forward Propagation(Manual)
images = images.numpy().squeeze()

Y_man = np.zeros(shape=(n_H - k_size + 1, n_W - k_size + 1, n_filter))
for c in range(n_filter):
  c_W = W[:, :, :, c]
  c_b = B[c]

  for h in range(n_H - k_size + 1):
    for j in range(n_W - k_size + 1):
      window = images[h:h+k_size, j:j+k_size, :]
      conv = np.sum(window*c_W) + c_b
      conv = 1/(1 + np.exp(-conv))

      Y_man[h, j, c] = conv

print("Output(Manual): \n", np.transpose(Y_man, (2, 0, 1)))

Output(Tensorflow): 
 [[[0.32978925 0.49754816]
  [0.3908566  0.44449478]]

 [[0.54379636 0.37718868]
  [0.3546539  0.34947342]]

 [[0.2918926  0.31088585]
  [0.17792696 0.38274288]]]
Output(Manual): 
 [[[0.32978923 0.49754818]
  [0.39085661 0.44449477]]

 [[0.54379637 0.37718865]
  [0.35465386 0.34947342]]

 [[0.29189264 0.3108858 ]
  [0.17792693 0.38274287]]]


(2, 3, 4) 

[[0 4 3]
 [1 8 1]]
[[7 2 3]
 [9 7 6]]
[[7 8 3]
 [3 6 7]]
[[8 6 8]
 [3 6 3]]


(4, 2, 3) 

[[0 4 3]
 [1 8 1]]
[[7 2 3]
 [9 7 6]]
[[7 8 3]
 [3 6 7]]
[[8 6 8]
 [3 6 3]]
