<a href="https://colab.research.google.com/github/answjddn005/Tensorflow-practice/blob/master/Max_Avg_Pooling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import MaxPooling1D

L, f, s = 10, 2, 1

x = tf.random.normal(shape=(1, L, 1))
pool_max = MaxPooling1D(pool_size=f, strides=s)
pooled_max = pool_max(x)

print("x :{}\n{}".format(x.shape, x.numpy().flatten()))
print("pooled_max(Tensorflow): {}\n{}".format(pooled_max.shape, 
                                              pooled_max.numpy().flatten()))

x = x.numpy().flatten()
pooled_max_man = np.zeros((L - f + 1, ))
for i in range(L-f+1):
  window = x[i:i+f]
  pooled_max_man[i] = np.max(window)

print("pooled_max(Manual): {}\n{}".format(pooled_max_man.shape, 
                                              pooled_max_man))


x :(1, 10, 1)
[-0.18905896  0.5111011   1.3330191  -0.84540987  1.3484836   1.1853542
 -1.0066805   0.791049    1.3933203   0.898295  ]
pooled_max(Tensorflow): (1, 9, 1)
[0.5111011 1.3330191 1.3330191 1.3484836 1.3484836 1.1853542 0.791049
 1.3933203 1.3933203]
pooled_max(Manual): (9,)
[0.51110113 1.33301914 1.33301914 1.34848356 1.34848356 1.18535423
 0.791049   1.39332032 1.39332032]


In [7]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import AveragePooling1D

L, f, s = 10, 2, 1

x = tf.random.normal(shape=(1, L, 1))
pool_avg = AveragePooling1D(pool_size=f, strides=s)
pooled_avg = pool_avg(x)

print("x :{}\n{}".format(x.shape, x.numpy().flatten()))
print("pooled_avg(Tensorflow): {}\n{}".format(pooled_avg.shape, 
                                              pooled_avg.numpy().flatten()))

x = x.numpy().flatten()
pooled_avg_man = np.zeros((L - f + 1, ))
for i in range(L-f+1):
  window = x[i:i+f]
  pooled_avg_man[i] = np.mean(window)

print("pooled_max(Manual): {}\n{}".format(pooled_avg_man.shape, 
                                              pooled_avg_man))


x :(1, 10, 1)
[ 0.04790678  0.04824657  2.9320283  -0.21626608  0.47758    -0.01656521
  1.0932708  -0.38689512  0.36148083  1.6220754 ]
pooled_avg(Tensorflow): (1, 9, 1)
[ 0.04807667  1.4901375   1.3578811   0.13065696  0.2305074   0.5383528
  0.35318783 -0.01270714  0.99177814]
pooled_max(Manual): (9,)
[ 0.04807667  1.49013746  1.35788107  0.13065696  0.2305074   0.53835279
  0.35318783 -0.01270714  0.99177814]


In [11]:
from tensorflow.keras.layers import MaxPooling2D

N, n_H, n_W, n_C = 1, 5, 5, 1
f, s = 2, 1

x = tf.random.normal(shape=(N, n_H, n_W, n_C))
pool_max = MaxPooling2D(pool_size=f, strides=s)
pooled_max = pool_max(x)

print("x :{}\n{}".format(x.shape, x.numpy().squeeze()))
print("pooled_max(Tensorflow): {}\n{}".format(pooled_max.shape, 
                                              pooled_max.numpy().squeeze()))

x = x.numpy().squeeze()
pooled_max_man = np.zeros(shape=(n_H - f + 1, n_W - f + 1))
for i in range(n_H - f + 1):
  for j in range(n_W - f + 1):
    window = x[i:i+f, j:j+f]
    pooled_max_man[i, j] = np.max(window) 

print("pooled_max(Manual): {}\n{}".format(pooled_max_man.shape, 
                                              pooled_max_man))

x :(1, 5, 5, 1)
[[-0.27465412  0.87974334  0.2197004  -1.3480613  -1.0445719 ]
 [-0.44962433  1.2642515  -0.34630805  1.9619604  -1.3671432 ]
 [-0.58714014  0.07181682 -0.726416    0.01838886 -1.8201611 ]
 [ 0.5379496  -1.7680538   0.84626526  1.1760838  -0.41010943]
 [-0.4559691   1.7272979   0.7789968  -1.6451849  -0.74323   ]]
pooled_max(Tensorflow): (1, 4, 4, 1)
[[1.2642515  1.2642515  1.9619604  1.9619604 ]
 [1.2642515  1.2642515  1.9619604  1.9619604 ]
 [0.5379496  0.84626526 1.1760838  1.1760838 ]
 [1.7272979  1.7272979  1.1760838  1.1760838 ]]
pooled_max(Manual): (4, 4)
[[1.26425147 1.26425147 1.96196043 1.96196043]
 [1.26425147 1.26425147 1.96196043 1.96196043]
 [0.53794962 0.84626526 1.1760838  1.1760838 ]
 [1.7272979  1.7272979  1.1760838  1.1760838 ]]


In [15]:
from tensorflow.keras.layers import AveragePooling2D

N, n_H, n_W, n_C = 1, 5, 5, 1
f, s = 2, 1

x = tf.random.normal(shape=(N, n_H, n_W, n_C))
pool_avg = AveragePooling2D(pool_size=f, strides=s)
pooled_avg = pool_avg(x)

print("x :{}\n{}".format(x.shape, x.numpy().squeeze()))
print("pooled_avg(Tensorflow): {}\n{}".format(pooled_avg.shape, 
                                              pooled_avg.numpy().squeeze()))

x = x.numpy().squeeze()
pooled_avg_man = np.zeros(shape=(n_H - f + 1, n_W - f + 1))
for i in range(n_H - f + 1):
  for j in range(n_W - f + 1):
    window = x[i:i+f, j:j+f]
    pooled_avg_man[i, j] = np.mean(window) 

print("pooled_avg(Manual): {}\n{}".format(pooled_avg_man.shape, 
                                              pooled_avg_man))

x :(1, 5, 5, 1)
[[ 0.35565454 -1.1223693   0.22816773 -1.8890556  -1.2630937 ]
 [-0.21905836  1.2392704  -1.5991311   1.5438426  -1.6653937 ]
 [ 0.9798018   0.09960563  0.14231558  0.11608782 -0.24272868]
 [ 1.5296876   0.4211236  -0.2478724   0.3031892   0.47924376]
 [-2.4003823   1.2049601  -0.44760588 -0.457039    0.5025602 ]]
pooled_avg(Tensorflow): (1, 4, 4, 1)
[[ 0.06337434 -0.31351554 -0.42904407 -0.81842506]
 [ 0.52490485 -0.02948486  0.05077871 -0.062048  ]
 [ 0.75755465  0.1037931   0.07843004  0.16394803]
 [ 0.18884727  0.23265135 -0.21233203  0.20698853]]
pooled_avg(Manual): (4, 4)
[[ 0.06337434 -0.31351554 -0.42904407 -0.81842506]
 [ 0.52490485 -0.02948486  0.05077871 -0.062048  ]
 [ 0.75755465  0.1037931   0.07843004  0.16394803]
 [ 0.18884727  0.23265135 -0.21233203  0.20698853]]
